### ISSUE TITLE
Unpacking DLC data

### ISSUE THREAD

**Issue by naiyt** [Atvaark/BinderTool#10]
First off, big thanks for the tool. I'm the guy that runs MugenMonkey currently and BinderTool was invaluable for extracting all of the scaling and infusion data.

Ashes of Ariandel was released today, and I'm looking to update the site with the new equipment data. Looks like it added `DLC1.bdt` and `DLC1.bhd`. I'm not sure I fully understand how BinderTool works, but I believe in order to start I'd need the key to decrypt `DLC1.bhd` which should give me the key to decrypt `DLC1.bdt`. Is that right?

@Atvaark do you have any interest in unpacking the DLC data? If not, I'd be happy to dive in and try to figure things out. Would you be able to point me in the right direction -- particularly with regards to what I'd need to do to find those keys?

Thanks!

**Comment by naiyt** [comment]
Actually, on second investigation it seems the files I need are actually in Data1.bdt -- seems they released all that with patch 1.08, not the actual DLC. (Makes sense, because the weapon data has to be available to all players, for multiplayer reasons.)

So as it stands, look like I don't actually need access to `DLC1.bdt` currently (but maybe someone else will down the line?).

**Comment by Atvaark** [comment]
I could take a look at the dlc files if someone sends them to me or I get bored and purchase it.

I'd have to figure out which encryption the file is using, extract the RSA/AES keys from the game and release a new version of the tool that can decrypt the dlc files.

Also someone would have to play the DLC with a tool that logs the file names in the archive. I haven't done that since the initial release of DS3, so that would also require some research first.

**Comment by naiyt** [comment]
Interesting, thanks. Sounds like it's pretty non trivial. I was able to get all the scaling data I needed out of Data1.bdt and Data0.bdt so I'm good to go now. I suppose we'd only need to unpack the DLC files if someone wanted access to the models/textures/etc for the DLC.

**Comment by Atvaark** [comment]
[v0.4.2](https://github.com/Atvaark/BinderTool/releases/tag/v0.4.2) can unpack the DLC1 archive now.

**Comment by naiyt** [comment]
Nice, that was fast!
