### ISSUE TITLE
Byte array size limit

### ISSUE THREAD

**Issue by TBulbaDB** [Atvaark/BinderTool#43]
Not sure if this project is somewhat still maintained, but I'm trying to use it for the new E\den Ring.

The file size is 10.932.196.539 bytes so it's bigger than max array size, therefore failing.

https://github.com/Atvaark/BinderTool/blob/84bdc675035754d33b56812f1606a20277e41137/BinderTool.Core/Enc/EncFile.cs#L44

Any suggestions?

**Comment by Atvaark** [comment]
I haven't checked how FROM changed the formats yet and I'm currently not planning to add support for it to this tool.

I reckon it's based on the Sekiro version since there is a oo2core_6_win64.dll file in the steam depot files.
Since these bdt archives are now multi-gb huge it'll take some effort to change all the unpacking code to streaming the files in smaller chunks instead of reading them entirely.

**Comment by TBulbaDB** [comment]
Thank you for the clarification. I'll give it a try and send a PR if I succeed.

**Comment by Atvaark** [comment]
Thanks. Any help is appreciated. You should base your changes on the Sekiro Branch https://github.com/Atvaark/BinderTool/commits/sekiro. 
Don't worry about adding backwards compatibility and or repacking for now. Just creating a working extractor should be a good first step.

**Comment by TBulbaDB** [comment]
Sorry, I won't be able to do the update.

**Comment by googleben** [comment]
Fixed with fe7cd3f3788a6800cb86e8f6970d173a900726d4.
