### ISSUE TITLE
Dark Souls II Extraction Issues

### ISSUE THREAD

**Issue by Grendor** [Atvaark/BinderTool#9]
Using the proper 0.3 version, extraction of Dark Souls II is inaccurate. Many of the extracted files are unidentified beyond extension. In respective folders, expected 'pairs' are missing  their partner files. c---.bnd or c---.texbnd are commonly missing from expected pairs, certain pairs missing entirely.

Scholar of the First Sin fails to extract any character/npc/enemy files at all, as well.

**Comment by theonlyShiro** [comment]
I have to say for me, everything went well . all maps / objects / models / animations were extracted and also works.

**Comment by Atvaark** [comment]
Many files are missing their related files because file name dictionary in 0.3 has lots of invalid names in it.
Someone would have to search for all the file names for it to work properly.
You could try to remove all file names besides the *cXXXX* files and maybe you'll get the ones you need.

There might also be some extracting/decrypting bugs I have only fixed in the DSIII version of this tool.

SotFS was never supported.
